issuer: https://dex.egoavara.net/
enablePasswordDB: false

# See https://dexidp.io/docs/storage/ for more options
storage:
  type: etcd
  config:
    endpoints:
      - http://etcd-dex.persistence.svc:2379
    username: root
    password: 9704df95-2c07-488b-a9b4-156754606c0b
    namespace: dex/

staticClients:
  - id: www.egoavara.net
    redirectURIs:
      - 'https://www.egoavara.net/callback'
    name: 'www.egoavara.net'
    secret: 0f8d9b9a-8b9a-4b9e-9b0e-9b9a8b9a8b9a
    public: true
  - id: jaeger
    redirectURIs:
      - 'https://jaeger.egoavara.net/oauth2/callback'
    name: 'jaeger'
    secret: '79126efe-008c-4adf-a421-2d8dd307e0e5'
  - id: prometheus
    redirectURIs:
      - 'https://prometheus.egoavara.net/oauth2/callback'
    name: 'prometheus'
    secret: '1184fb37-0e30-422d-9ecd-487fda27af05'


connectors:
  - type: ldap
    id: ldap
    name: LDAP
    config:
      host: openldap.persistence.svc:389

      insecureNoSSL: true
      insecureSkipVerify: true

      bindDN: cn=admin,dc=egoavara,dc=net
      bindPW: fdffbd16-c045-4d89-8ec7-d65606ee84ac

      usernamePrompt: SSO Username

      userSearch:
        baseDN: ou=users,dc=egoavara,dc=net

        username: uid
        idAttr: uid
        emailAttr: uid
        nameAttr: uid
        preferredUsernameAttr: uid