apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: persistence

resources:
  - resources/namespace.yaml
  - resources/ldap.yaml
  - resources/kafka.yaml
  - resources/postgres-svc.yaml
  - resources/elasticsearch.yaml
  - resources/elasticsearch-telemetry.yaml

generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:
  - name: postgres-svc-migration
    files:
      - "./configs/postgres-svc-migration/migration.sql"
      - "./configs/postgres-svc-migration/run.sh"

secretGenerator:
  - name: secret-ldap
    envs:
      - "./secrets/secret-ldap.env"
  - name: secret-postgres-openfga
    envs:
      - "./secrets/secret-postgres-openfga.env"
  - name: secret-postgres-svc
    envs:
      - "./secrets/secret-postgres-svc.env"
  - name: secret-kafka-connect
    files:
      - "./secrets/secret-kafka-connect.env"
  - name: etcd-dex-auth
    envs:
      - "./secrets/etcd-dex-auth.env"

helmCharts:
  # postgres for openfga
  - repo: https://charts.bitnami.com/bitnami
    name: postgresql
    namespace: persistence
    releaseName: postgres-openfga
    version: 13.2.3
    valuesFile: ./values/postgres-openfga.yaml
  # postgres for svc
  - repo: https://charts.bitnami.com/bitnami
    name: postgresql
    namespace: persistence
    releaseName: postgres-svc
    version: 13.2.3
    valuesFile: ./values/postgres-svc.yaml
  # etcd for dex
  - repo: https://charts.bitnami.com/bitnami
    name: etcd
    namespace: persistence
    releaseName: etcd-dex
    version: 9.8.0
    valuesFile: ./values/etcd-dex.yaml
  # redis (key-value store)
  #  - releaseName: redis
  #    repo: https://charts.bitnami.com/bitnami
  #    name: redis
  #    version: 18.3.0
  #    valuesFile: ./values/redis.yaml
  # neo4j (graph database)
#  - releaseName: neo4j
#    repo: https://helm.neo4j.com/neo4j
#    name: neo4j
#    version: 5.14.0
#    valuesFile: ./values/neo4j.yaml