nameOverride: hasura-svc
namespaceOverride: service

secret:
  enabled: false
  name: hasura-svc-secret
  metadataDbUrl: test
config:
  extraConfigs:
    HASURA_GRAPHQL_ENABLE_APOLLO_FEDERATION: "true"
extraEnvs:
  - name: HASURA_GRAPHQL_ADMIN_SECRET
    valueFrom:
      secretKeyRef:
        name: hasura-svc-secret
        key: HASURA_GRAPHQL_ADMIN_SECRET
  - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: hasura-svc-secret
        key: HASURA_GRAPHQL_METADATA_DATABASE_URL
  - name: HASURA_GRAPHQL_DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: hasura-svc-secret
        key: HASURA_GRAPHQL_DATABASE_URL
postgres:
  enabled: false
