apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:latest
          imagePullPolicy: "Always"
          env:
            - name: LDAP_PORT_NUMBER
              value: "389"
            - name: LDAP_ROOT
              value: dc=egoavara,dc=net
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: admin-password
                  name: secret-ldap
            - name: LDAP_USERS
              valueFrom:
                secretKeyRef:
                  key: usernames
                  name: secret-ldap
            - name: LDAP_PASSWORDS
              valueFrom:
                secretKeyRef:
                  key: passwords
                  name: secret-ldap
          ports:
            - name: tcp-ldap
              containerPort: 389
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: 389
      targetPort: 389
  selector:
    app.kubernetes.io/name: openldap
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ldap-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 389
        name: tcp-ldap
        protocol: TCP
      hosts:
        - "ldap.egoavara.net"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ldap-virtualservice
spec:
  hosts:
    - "ldap.egoavara.net"
  gateways:
    - ldap-gateway
  tcp:
    - match:
        - port: 389
      route:
        - destination:
            host: openldap
            port:
              number: 389