apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dex-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: credential-dex
      hosts:
        - "dex.egoavara.net"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dex-virtualservice
spec:
  hosts:
    - "dex.egoavara.net"
  gateways:
    - dex-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: dex
            port:
              number: 5556