apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migration
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: postgres-migration
          image: bitnami/postgresql:16.0.0-debian-11-r15
          command: ["/bin/bash", "-f", "/var/configs/migration/run.sh"]
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-postgres-svc
                  key: svc-password
          volumeMounts:
            - name: postgres-svc-migration
              mountPath: /var/configs/migration
      restartPolicy: Never
      volumes:
        - name: postgres-svc-migration
          configMap:
            name: postgres-svc-migration
  backoffLimit: 4