apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/istio-credentials.yaml
  - resources/minio-operator.yaml

helmCharts:
  # letsencrypt 인증서 관리도구
  - releaseName: certmanager-operator
    repo: https://charts.bitnami.com/bitnami
    name: cert-manager
    version: 0.13.2
    namespace: cert-manager
    valuesFile: ./values/certmanager-operator.yaml
    includeCRDs: true
  # elasticsearch 관리도구
  - releaseName: eck-operator
    repo: https://helm.elastic.co
    name: eck-operator
    version: 2.10.0
    namespace: eck-operator
    valuesFile: ./values/eck-operator.yaml
    includeCRDs: true
  # Confluent 관리도구
  - releaseName: confluent-operator
    repo: https://packages.confluent.io/helm
    name: confluent-for-kubernetes
    version: 0.824.33
    namespace: confluent-operator
    valuesFile: ./values/confluent-operator.yaml
    includeCRDs: true
  # jaeger 관리도구
  - releaseName: jaeger-operator
    repo: https://jaegertracing.github.io/helm-charts
    name: jaeger-operator
    version: 2.49.0
    namespace: jaeger-operator
    valuesFile: ./values/jaeger-operator.yaml
    includeCRDs: true
  # kiali 관리도구
  - releaseName: kiali-operator
    repo: https://kiali.org/helm-charts
    name: kiali-operator
    version: 1.78.0
    namespace: kiali-operator
    valuesFile: ./values/kiali-operator.yaml
    includeCRDs: true
  # istio, base
  - releaseName: istio-base
    repo: https://istio-release.storage.googleapis.com/charts
    name: base
    version: 1.20.1
    namespace: istio-system
    valuesFile: ./values/istio-base.yaml
    includeCRDs: true
  # istio, istiod
  - releaseName: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    name: istiod
    version: 1.20.1
    namespace: istio-system
    valuesFile: ./values/istio-istiod.yaml
    includeCRDs: true
  # istio, gateway
  - releaseName: ingressgateway
    repo: https://istio-release.storage.googleapis.com/charts
    name: gateway
    version: 1.20.1
    namespace: istio-system
    valuesFile: ./values/istio-ingressgateway.yaml
    includeCRDs: true
  # prometheus 관리도구
  - releaseName: prometheus-operator
    repo: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 55.5.1
    namespace: prometheus-operator
    valuesFile: ./values/prometheus-operator.yaml
    includeCRDs: true
  # minio 관리도구
  - releaseName: minio-operator
    repo: https://operator.min.io/
    name: operator
    version: 5.0.11
    namespace: minio-operator
    valuesFile: ./values/minio-operator.yaml
    includeCRDs: true