apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer
  namespace: istio-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: egoavara@gmail.com
    privateKeySecretRef:
      name: telemetry-issuer
    solvers:
      #      - http01:
      #          ingress:
      #            #            ingressClassName: istio
      #            class: istio
      - dns01:
          cloudDNS:
            # The ID of the GCP project
            project: practice-make-perfect-379914
            # This is the secret used to access the service account
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: credential-minio-operator
  namespace: istio-system
spec:
  secretName: credential-minio-operator
  issuerRef:
    name: issuer
  dnsNames:
    - minio.egoavara.net
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: credential-telemetry
  namespace: istio-system
spec:
  secretName: credential-telemetry
  issuerRef:
    name: issuer
  dnsNames:
    - jaeger.egoavara.net
    - prometheus.egoavara.net
    - kiali.egoavara.net
    - grafana.egoavara.net
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: credential-dex
  namespace: istio-system
spec:
  secretName: credential-dex
  issuerRef:
    name: issuer
  dnsNames:
    - dex.egoavara.net
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: credential-dummy
  namespace: istio-system
spec:
  secretName: credential-dummy
  issuerRef:
    name: issuer
  dnsNames:
    - dummy.egoavara.net