apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer
  namespace: istio-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: egoavara@gmail.com
    privateKeySecretRef:
      name: telemetry-issuer
    solvers:
      - http01:
          ingress:
            class: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: credential-minio-operator
  namespace: istio-system
spec:
  secretName: credential-minio-operator
  issuerRef:
    name: issuer
  dnsNames:
    - minio.egoavara.net
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: credential-telemetry
  namespace: istio-system
spec:
  secretName: credential-telemetry
  issuerRef:
    name: issuer
  dnsNames:
    - jaeger.egoavara.net
    - prometheus.egoavara.net
    - kiali.egoavara.net
    - grafana.egoavara.net
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: credential-dex
  namespace: istio-system
spec:
  secretName: credential-dex
  issuerRef:
    name: issuer
  dnsNames:
    - dex.egoavara.net