name: "ingressgateway"

service:
  # Type of service. Set to "None" to disable the service entirely
  type: LoadBalancer
  ports:
    - name: tcp-status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: tcp-http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: tcp-ldap
      port: 389
      protocol: TCP
      targetPort: 389
    - name: tcp-https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: tcp-ldaps
      port: 636
      protocol: TCP
      targetPort: 636
    - name: tcp-postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
