global:
  proxy:
    tracer: "zipkin"
  tracer:
    zipkin:
      address: "jaeger-collector.telemetry.svc:9411"
meshConfig:
  defaultConfig:
    tracing:
      sampling: 100
  extensionProviders:
    - name: otel
      envoyOtelAls:
        service: jaeger-collector.istio-system.svc
        port: 4317
