replicaCount: 1

datastore:
  engine: postgres
  uriSecret: "openfga-datastore"

postgresql:
  auth:
    postgresPassword: password
    database: openfga

authn:
  method:
  preshared:
    keys: []
  oidc:
    audience:
    issuer:

playground:
  enabled: true
  port: 3000

ingress:

  enabled: false
image:
  tag: "v1.4.2"

telemetry:
  trace:
    enabled: true
    otlp:
      endpoint: jaeger-collector.telemetry.svc:4317
      tls:
        enabled: false
    sampleRatio: 100

openfga:
  selectorLabels:
    app: openfga

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# @param sidecars Add additional sidecar containers to the pods
# Example:
# sidecars:
#   - name: your-image-name
#     image: your-image
#     imagePullPolicy: Always
#     ports:
#       - name: portname
#         containerPort: 1234
sidecars: []