apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: telemetry
spec:
  strategy: production
  ingress:
    enabled: false
  agent:
    strategy: DaemonSet
  storage:
    elasticsearch:
      doNotProvision: true
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-telemetry-es-http.persistence.svc:9200
        index-prefix: jaeger


  #  strategy: allInOne


#  strategy: production
#  collector:
#    maxReplicas: 1
#    resources:
#      limits:
#        cpu: 100m
#        memory: 128Mi
#  storage:
#    type: memory
#    options:
#      memory:
#        max-traces: 100000
#  ingress:
#    enabled: false
#  agent:
#    strategy: DaemonSet
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger-virtualservice
  namespace: telemetry
spec:
  hosts:
    - "jaeger.egoavara.net"
  gateways:
    - gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: oauth2proxy-jaeger
            port:
              number: 80