apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  labels:
    app: dex
    version: 2.37.0
spec:
  selector:
    matchLabels:
      app: dex
      version: 2.37.0
  template:
    metadata:
      labels:
        app: dex
        version: 2.37.0
