apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfga
  labels:
    app: openfga
    version: 1.3.10
spec:
  selector:
    matchLabels:
      app: openfga
      version: 1.3.10
  template:
    metadata:
      labels:
        app: openfga
        version: 1.3.10